### ISSUE TITLE
[CI/CD] Run rubocop when ruby code changes

### ISSUE THREAD

**Issue by nguyenxuanhung-rightsvn** [nguyenxuanhung2304/ruby-on-moon#28]
## About this feature
Run rubocop when ruby code changes

## Notes
Try change code as bellow:
```
// .github/workflows/rubocop.yml
on:
  pull_request:
    paths:
      - '**/*.rb'
      - '*.rb'
```
